### PR TITLE
Add a chat highlighter and clean up chat channels.

### PR DESCRIPTION
**Pull request by wizjany**
## Highlights
- `/highlight keyword keyword ...` sets the player's highlight keywords. (defaults to the player's name)
- `/highlightsound -d` will disable "pings" when highlights occur
- `/highlightsound sound.name` will choose a sound name (note.pling by default)

All settings are persistent.
## Channels
- `/who` command lists players currently in channel, including those who went offline

Channels are _not_ persistent, they must be rejoined when the server restarts (or plume reloads) but NOT when a user relogs.

### CODE REVIEW

**Comment by hedgehog1029** [comment]
Thanks Wiz, been meaning to clean this up for a while now. And thanks for highlights, was having trouble with that.

**Comment by wizjany** [comment]
yea mojang's chat component thing is a pain. have to split and make a new subcomponent every single time you want to change formatting.

**Comment by hedgehog1029** [comment]
Agreed, it's a massive pain.

**Comment by hedgehog1029** [comment]
Ok, after this was put on Alice, it appears completely broken. I'm probably gonna revert the commits so we can have working chatchannels again.

**Pull request merged**
